# The layout of this form has two columns:
columns:
  - width: 1/2
    sections:
      projects: sections/projects

  - width: 1/2
    sections:
      pages:
        type: pages
        templates:
          - home
          - page
          - projects
          - team
          - default
