title: Dashboard

tabs:
  content:
    columns:
      - width: 1/2
        sections:
          projects: sections/projects

      - width: 1/2
        sections:
          pages:
            type: pages
            templates:
              - page
              - home
              - projects
              - team
  seo:
    label: SEO
    icon: search
    fields:
      info:
        label:
        type: info
        text: ℹ️ Site wide SEO settings, these maybe be overwritted on individual pages by titles, subheading and cover images.
      seoTitle:
        label: SEO title
        type: text
      seoDescription:
        label: SEO description
        type: text
      seoImage:
        label: SEO Image
        type: files
        multiple: false
        layout: cards
        size: large
